version: '3.8'

services:
  flask-app:
    build: 
      context: ./app
      args:
        USER_ID: ${UID:-1000}
    volumes:
      - ./app:/app
      - ./logs:/app/logs
    environment:
      - FLASK_ENV=development
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask-app
    networks:
      - app-network

networks:
  app-network:
